### ISSUE TITLE
Error DriverPackageNotInstalledError

### ISSUE THREAD

**Issue by Kllngii** [r6db/app#30]
When I download the latest version of this project and follow the instructions of the readme I got this error. ```{ DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/error/DriverPackageNotInstalledError.js:19:28)
    at SqliteDriver.loadDependencies (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/sqlite/SqliteDriver.js:144:19)
    at new SqliteDriver (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/sqlite/SqliteDriver.js:70:15)
    at DriverFactory.create (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/DriverFactory.js:32:24)
    at new Connection (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/connection/Connection.js:89:59)
    at ConnectionManager.create (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:230:66)
    at step (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:32:23)
    at Object.next (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:13:53)
    at /Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:7:71
  name: 'DriverPackageNotInstalledError',
  message: 'SQLite package has not been found installed. Try to install it: npm install sqlite3 --save' } Promise {
  <rejected> { DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/error/DriverPackageNotInstalledError.js:19:28)
    at SqliteDriver.loadDependencies (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/sqlite/SqliteDriver.js:144:19)
    at new SqliteDriver (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/sqlite/SqliteDriver.js:70:15)
    at DriverFactory.create (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/driver/DriverFactory.js:32:24)
    at new Connection (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/connection/Connection.js:89:59)
    at ConnectionManager.create (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:230:66)
    at step (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:32:23)
    at Object.next (/Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:13:53)
    at /Users/lasse_kelling/Desktop/app-master 21.40.23/packages/core/node_modules/typeorm/index.js:7:71
  name: 'DriverPackageNotInstalledError',
  message: 'SQLite package has not been found installed. Try to install it: npm install sqlite3 --save' } }```

I tried to fix this with:
npm: ``` npm install sqlite3 --save```
Yarn: ``` yarn add sqlite3```
lerna: ``` lerna add sqlite3```
npm global: ``` npm install sqlite3 -g --save```
yarn global: ``` yarn global add sqlite3```

And it didn`t work. I tried all these ways in the project-root and the packages/desktop/
If I ignore the error I only can see the background of the app.

**Comment by LaxisB** [comment]
this is caused because we need to compile sqlite for electron.
you can fix this by runnung `lerna run build-deps` in the root directory, or directly in packages/desktop as yarn task.  
i've updated the readme to reflect this
